dataset: cgqa
clip_model: ViT-L/14
seed: 0
epochs: 20
lr: 0.00001
loss: GenCSPLoss
label_smooth: 0.01
partial_smooth: True
attr_dropout: 0.3
weight_decay: 0.00001
train_batch_size: 64
eval_batch_size: 64
gradient_accumulation_steps: 2
best_model_metric: AUC
context_length: 8
text_db: 'opt_sentences64_all_pairs_closed.pkl'
num_texts: 64
group_gauss: True
num_aug: 8
attn_dropout: 0.1
tune_vit: True
use_gauss: True
with_group: True
disentangle: True
fusion: True
fusion_factor: beta
use_attrobj_gauss: True
w_attr: 0.01
w_obj: 0.01
save_path: output/cgqa/fullmodel
save_every_n: 2
num_workers: 4
pin_memory: True